apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-webapp
spec:
  selector:
      matchLabels:
        app: people-webapp
  replicas: 2
  template:
      metadata:
        labels:
            app: people-webapp
      spec:
        containers:
        - name: people-webapp
          image: people.azurecr.io/people.webapp:v1
          ports:
          - containerPort: 5000            
---
apiVersion: v1
kind: Service
metadata:
  name: people-webapp-svc  
spec:
  selector:
    app: people-webapp
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
